# Generated by Django 5.1.1 on 2024-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ebfe476e-1826-4af4-bec7-07acccc1c953', max_length=100, primary_key=True, serialize=False),
        ),
    ]
