# Generated by Django 5.1.1 on 2024-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='a02ba5dc-96f9-4d37-b76b-944892926aaa', max_length=100, primary_key=True, serialize=False),
        ),
    ]
